# Configuration file for the release notes builder
version: "1.0"

password_file: ./.passwords.yaml
templates_directory: ./templates
jira_batch_size: 50

release_settings:

  - name: couchbase-mobile
    url: https://issues.couchbase.com
    jql: project = CBL AND issuetype in (Bug, Improvement)
      AND Status = Closed
      AND Resolution = Fixed
      AND Component in (.NET, C, IOS, Java, Java-Android, Kotlin, Kotlin-Android, LiteCore)
      AND Level = 'Public'
      AND fixVersion = {{release_number}}

    fields:
      - name: module
        type: select
        message: 'Select module:'
        choices:
          - Android
          - C
          - .NET
          - Java
          - Javascript
          - Objective-C
          - Swift
      - name: release_number
        type: text
        message: 'Enter the release number:'

    template: couchbase-mobile.jinja2

  - name: docs-server
    url: https://issues.couchbase.com
    jql: project = MB AND issuetype = Bug
      AND status = Closed
      AND resolution = Fixed
      AND fixVersion IN ({{release_number}})
      AND component in (analytics, eventing, fts, ns_server, query, query_tools, 
      rbac, XDCR, memcached, secondary-index, installer, storage-engine, view-engine)

    fields:
      - name: release_date
        type: text
        message: 'Enter the release date (Month Year):'
      - name: release_number
        type: text
        message: 'Enter the release number:'

    template: couchbase-docs-server.jinja2

  - name: sync-gateway
    url: https://issues.couchbase.com
    jql: project = CBG AND type in (Bug, "New Feature", Epic, Improvement) AND fixVersion = {{release_number}} AND level = "Public" ORDER BY id DESC

    fields:
      - name: release_number
        type: text
        message: 'Enter the release number:'
      - name: release_date
        type: text
        message: 'Enter the release date (Month Year):'
      - name: note
        type: multiline
        message: 'Enter a note for the release:'

    template: sync-gateway.jinja2

  - name: sync-gateway-ki
    url: https://issues.couchbase.com
    jql: project = CBG AND labels in (known_issue) AND status not in (Closed, Resolved) ORDER BY id DESC

    template: sync-gateway-ki.jinja2