# Configuration file for the release notes builder
version: "1.0"

password_file: ./.passwords.yaml
templates_directory: ./templates
jira_batch_size: 50

release_settings:

  - name: couchbase-mobile
    url: https://issues.couchbase.com
    jql: project = CBL AND issuetype in (Bug, Improvement)
      AND Component in (.NET, C, IOS, Java, Java-Android, Kotlin, Kotlin-Android, LiteCore)
      AND Level = 'Public'
      AND (fixVersion = {{release_number}} OR labels IN (known_issue))
    fields:
      - name: module
        type: select
        message: 'Select module:'
        choices:
          - Android
          - C
          - .NET
          - Java
          - Javascript
          - Objective-C
          - Swift
      - name: release_number
        type: text
        message: 'Enter the release number:'
      - name: release_date
        type: text
        message: 'Enter the release date (month year)'
    template: couchbase-mobile.jinja2

  - name: docs-server
    url: https://issues.couchbase.com
    jql: project = "Couchbase Server" 
         AND fixVersion = {{release_number}} 
         AND (labels = releasenote OR summary ~ BP) 
         AND (level is EMPTY OR level != Private) 
         AND resolution in (Fixed)
         AND component in (analytics, eventing, fts, ns_server, query, query_tools,
         rbac, XDCR, memcached, secondary-index, installer, 
         storage-engine, view-engine, couchbase-bucket)
    fields:
      - name: release_date
        type: text
        message: 'Enter the release date (Month Year):'
      - name: release_number
        type: text
        message: 'Enter the release number:'
    template: couchbase-docs-server.jinja2

  - name: sync-gateway
    url: https://issues.couchbase.com
    jql: project = CBG AND issuetype in (Bug, "New Feature", Epic, Improvement) 
      AND (fixVersion = {{release_number}} OR labels IN (known_issue))
      AND level = "Public" ORDER BY id DESC
    fields:
      - name: release_number
        type: text
        message: 'Enter the release number:'
      - name: release_date
        type: text
        message: 'Enter the release date (Month Year):'
    template: sync-gateway.jinja2

